# -*- coding: utf-8 -*-
"""promotions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17jTOjLrsCNmqWDBC1Tr6ZnA2F3cDvw9C
"""

import streamlit as st
import pandas as pd
import re
import firebase_admin
from firebase_admin import credentials, firestore
from datetime import datetime, timedelta
import google.generativeai as genai

# ---------- FIREBASE SETUP ---------- #
if not firebase_admin._apps:
    cred = credentials.Certificate('/content/restaurant-data-backend-firebase-adminsdk-fbsvc-121da829d8.json')
    firebase_admin.initialize_app(cred)

db = firestore.client()

# ---------- GEMINI SETUP ---------- #
genai.configure(api_key="AIzaSyChafmWRd4eP8nUFtouDzjVcpVt1TXas7c")
model = genai.GenerativeModel('models/gemini-1.5-pro')

# ---------- STREAMLIT SETUP ---------- #
st.set_page_config(page_title="AI Menu Recommender", layout="wide")

# ---------- NAVIGATION ---------- #
page = st.sidebar.selectbox("Choose Page", ["🍽️ AI Dish Recommender", "🏆 Staff Rankboard"])

if page == "🍽️ AI Dish Recommender":
    st.title("🍽️ AI-Driven Marketing Campaign Recommender")

    staff_name = st.text_input("Enter your name")
    staff_uid = st.text_input("Enter your UID")

    menu_docs = db.collection('menu').stream()
    menu_data = [doc.to_dict() for doc in menu_docs]
    menu_df = pd.DataFrame(menu_data)

    inv_docs = db.collection('ingredient_inventory').stream()
    inventory_data = [doc.to_dict() for doc in inv_docs]
    inventory_df = pd.DataFrame(inventory_data)

    def parse_quantity(qty):
        match = re.match(r"([\d\.]+)\s*(\w+)", str(qty).lower())
        return (float(match.group(1)), match.group(2)) if match else (None, None)

    def standardize_quantity(qty, unit):
        if unit == 'kg': return qty * 1000
        elif unit == 'g': return qty
        elif unit == 'l': return qty * 1000
        elif unit == 'ml': return qty
        elif unit in ['pcs', 'pieces', 'piece']: return qty
        else: return None

    inventory_df['Expiry Date'] = pd.to_datetime(inventory_df['Expiry Date'], dayfirst=True)
    inventory_df[['qty_val', 'qty_unit']] = inventory_df['Quantity'].apply(lambda x: pd.Series(parse_quantity(x)))
    inventory_df['std_qty'] = inventory_df.apply(lambda row: standardize_quantity(row['qty_val'], row['qty_unit']), axis=1)

    today = datetime.now()
    valid_ingredients_df = inventory_df[
        (inventory_df['Expiry Date'] > today) &
        (inventory_df['std_qty'] > 0)
    ]
    available_ingredients = valid_ingredients_df['Ingredient'].str.lower().tolist()

    possible_dishes = []
    for _, row in menu_df.iterrows():
        req_ings = [i.strip().lower() for i in row['ingredients'].split(',')]
        if all(ing in available_ingredients for ing in req_ings):
            possible_dishes.append(row['name'])

    st.success("Dishes that can be made today:")
    st.write(possible_dishes)

    with st.form("promotion_form"):
        promo_type = st.selectbox("Promotion Type", ["Buy 1 Get 1", "Discount", "Combo Offer"])
        promo_goal = st.text_input("Promotion Goal (e.g., Reduce waste, Boost sales)")
        submit = st.form_submit_button("Generate Campaign")

    if submit and possible_dishes:
        prompt = f"""
        You are a restaurant marketing expert.
        Dishes available today: {', '.join(possible_dishes)}
        Promotion type: {promo_type}
        Goal: {promo_goal}
        Create a creative and specific campaign using only these dishes.
        """
        with st.spinner("Generating campaign..."):
            response = model.generate_content(prompt)
            campaign = response.text
        st.subheader("📢 Generated Marketing Campaign")
        st.write(campaign)

        current_month = datetime.now().strftime("%Y-%m")
        campaign_doc = {
            "uid": staff_uid,
            "name": staff_name,
            "campaign": campaign,
            "points": 0,
            "votes": 0,
            "sales": 0,
            "timestamp": firestore.SERVER_TIMESTAMP,
            "month": current_month
        }
        db.collection("staff_campaigns").document(f"{staff_uid}_{current_month}").set(campaign_doc)
        st.success("Campaign submitted and recorded for ranking!")

elif page == "🏆 Staff Rankboard":
    st.title("🏆 Staff Campaign Rankboard")
    current_month = datetime.now().strftime("%Y-%m")
    st.subheader(f"📅 Leaderboard for {current_month}")

    def calculate_score(votes, sales):
        return votes * 2 + sales * 5  # Weighted score

    campaign_docs = db.collection('staff_campaigns').where('month', '==', current_month).stream()
    leaderboard = []
    for doc in campaign_docs:
        data = doc.to_dict()
        score = calculate_score(data.get('votes', 0), data.get('sales', 0))
        db.collection('staff_campaigns').document(doc.id).update({'points': score})
        leaderboard.append({"Name": data.get("name"), "Points": score})

    if leaderboard:
        df_lb = pd.DataFrame(sorted(leaderboard, key=lambda x: x['Points'], reverse=True))
        st.dataframe(df_lb)

        if datetime.now().day == 1:
            top_staff = df_lb.iloc[0]['Name']
            st.success(f"🏅 This month's top performer: {top_staff}. PROMOTED!")
            # Log promotion history
            db.collection('staff_profiles').document(top_staff).set({
                'last_promotion': datetime.now(),
                'name': top_staff,
                'month': current_month
            }, merge=True)
            # Reset points for new month
            for doc in db.collection('staff_campaigns').where('month', '==', current_month).stream():
                db.collection('staff_campaigns').document(doc.id).delete()
    else:
        st.info("No campaigns recorded for this month.")